name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Extract version from tag
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          echo "BUILD_VERSION=$VERSION" >> "$GITHUB_ENV"
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Publish to Repository
        env:
          REPO_USER: ${{ secrets.REPO_USER }}
          REPO_PASS: ${{ secrets.REPO_PASS }}
          BUILD_VERSION: ${{ env.BUILD_VERSION }}
        run: ./gradlew publish
